### PR TITLE
added zoslib

### PR DESCRIPTION
**Pull request by HarithaIBM**

### CODE REVIEW

**Review by MikeFultonDev — COMMENTED** [review]
Did test case failures change ?

**Comment by HarithaIBM** [comment]
> Did test case failures change ?

Mike, There is no change in test case pass/fail percentage. Thank you

**Review by MikeFultonDev — APPROVED** [review]

**Comment by IgorTodorovskiIBM** [comment]
Is CMake still built in EBCDIC mode? @perry-ca?. If it is, I think it may be incompatible with zoslib. @HarithaIBM can you confirm if zoslib is being linked in by inspecting the build logs?

**Comment by perry-ca** [comment]
Yes it is.  This should be fine with zoslib as long as you don't define the override macros.  Just use the missing posix functions from zoslib.

**Pull request closed without merging**
