### PR TITLE
CMake 3.24.2 patch

### PR DESCRIPTION
**Pull request by fanbo-meng**
Update to CMake version 3.24.2 and add testing.

### CODE REVIEW

**Review by perry-ca — APPROVED** [review]
LGTM

**Review by MikeFultonDev — APPROVED** [review]
Thanks! Are there tests we can turn on?

**Comment by MikeFultonDev** [comment]
Sounds reasonable to me. You can change how testing is done by changing ZOPEN_CHECK ( see zopen build -? For env cars you can specify)

**Comment by fanbo-meng** [comment]
@MikeFultonDev I just added testing, can you review again? thanks!

**Review by MikeFultonDev — APPROVED** [review]
Looks good. I think there is another env var like ZOPEN_HOME that you can use to get the underlying dir which is better if you support both tarball and git builds

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
